let animalsList = {
    "🦁": "Lion",
    "🐵": "Monkey",
    "🦍": "Gorilla",
    "🦧": "Orangutan",
    "🐶": "Dog Face",
    "🐕": "Dog",
    "🐺": "Wolf",
    "🦊": "Fox",
    "🦝": "Raccoon",
    "🐱": "Cat Face",
    "🐈": "Cat",
    "🐈‍": "Black Cat",
    "🐯": "Tiger Face",
    "🐅": "Tiger",
    "🐆": "Leopard",
    "🐴": "Horse Face",
    "🐎": "Horse",
    "🦄": "Unicorn",
    "🦮": "Guide Dog",
    "🐕‍": "Service Dog",
    "🐩": "Poodle",
    "🦓": "Zebra",
    "🐒": "Monkey Sitting",
    "🦌": "Deer",
    "🦬": "Bison",
    "🐮": "Cow Face",
    "🐂": "Ox",
    "🐃": "Water Buffalo",
    "🐄": "Cow",
    "🐷": "Pig Face",
    "🐖": "Pig",
    "🐗": "Boar",
    "🐏": "Ram",
    "🐑": "Ewe",
    "🐐": "Goat",
    "🐪": "Camel",
    "🐫": "Two-Hump Camel",
    "🦙": "Llama",
    "🦒": "Giraffe",
    "🐘": "Elephant",
    "🦣": "Mammoth",
    "🦏": "Rhinoceros",
    "🦛": "Hippopotamus",
    "🐭": "Mouse Face",
    "🐁": "Mouse",
    "🐀": "Rat",
    "🐹": "Hamster",
    "🐰": "Rabbit Face",
    "🐇": "Rabbit",
    "🐿️": "Chipmunk",
    "🦫": "Beaver",
    "🦔": "Hedgehog",
    "🦇": "Bat",
    "🐻": "Bear",
    "🐻‍❄": "Polar Bear",
    "🐨": "Koala",
    "🐼": "Panda",
    "🦥": "Sloth",
    "🦦": "Otter",
    "🦨": "Skunk",
    "🦘": "Kangaroo",
    "🦡": "Badger",
    "🦃": "Turkey",
    "🐔": "Chicken",
    "🐓": "Rooster",
    "🐣": "Hatching Chick",
    "🐤": "Baby Chick",
    "🐥": "Front-Facing Baby Chick",
    "🐦": "Bird",
    "🐧": "Penguin",
    "🕊️": "Dove",
    "🦅": "Eagle",
    "🦆": "Duck",
    "🦢": "Swan",
    "🦉": "Owl",
    "🦤": "Dodo",
    "🦩": "Flamingo",
    "🦚": "Peacock",
    "🦜": "Parrot",
    "🐸": "Frog",
    "🐊": "Crocodile",
    "🐢": "Turtle",
    "🦎": "Lizard",
    "🐍": "Snake",
    "🐲": "Dragon Face",
    "🐉": "Dragon",
    "🦕": "Sauropod",
    "🦖": "T-Rex",
    "🐳": "Spouting Whale",
    "🐋": "Whale",
    "🐬": "Dolphin",
    "🦭": "Seal",
    "🐟": "Fish",
    "🐠": "Tropical Fish",
    "🐡": "Blowfish",
    "🦈": "Shark",
    "🐙": "Octopus",
    "🐌": "Snail",
    "🦋": "Butterfly",
    "🐛": "Bug",
    "🐜": "Ant",
    "🐝": "Honeybee",
    "🪲": "Beetle",
    "🐞": "Lady Beetle",
    "🦗": "Cricket",
    "🪳": "Cockroach",
    "🕷️": "Spider",
    "🦂": "Scorpion",
    "🦟": "Mosquito",
    "🪰": "Fly",
    "🦀": "Crab",
    "🦞": "Lobster",
    "🦐": "Shrimp",
    "🦑": "Squid"
  };

export { animalsList };